name: Slack Notification

on:
  pull_request:
    types:
      - opened

jobs:
  slack-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        id: slack
        uses: rtCamp/action-slack-notify@v3
        with:
          slack_message: |
            A new pull request has been created: ${{ github.event.pull_request.html_url }}
            Please review and approve the build.
          slack_channel: your_slack_channel
          slack_attachments: |
            [{
              "fallback": "Build Approval",
              "callback_id": "build_approval",
              "color": "#3AA3E3",
              "actions": [{
                "name": "approval",
                "text": "Approve",
                "type": "button",
                "value": "approved"
              }]
            }]
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Wait for Build Approval
        id: build-approval
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { data: pullRequest } = await github.pulls.get({
              owner,
              repo,
              pull_number: context.payload.pull_request.number
            });
            const { status, conclusion } = pullRequest;
            if (status === "success" && conclusion === "success") {
              console.log("Build approved.");
              return { approved: true };
            }
            return { approved: false };

      - name: Trigger Build
        if: steps.build-approval.outputs.approved == 'true'
        run: |
          # Add your build triggering command here
